# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       maui-rpm-config

# >> macros
# << macros
%define disable_docs_package 1

Summary:    MeeGo specific rpm configuration files
Version:    0.18
Release:    1
Group:      Development/System
License:    GPL+
BuildArch:  noarch
URL:        http://maui.com
Source0:    %{name}-%{version}.tar.xz
Source100:  maui-rpm-config.yaml
# Patches auto-generated by git-buildpackage:
Patch0:     0001-meego-rpm-config-0.18-merchanges.patch.patch
Patch1:     0002-meego-rpm-config-0.18-bashism.patch.patch
Patch2:     0003-meego-rpm-config-0.18-flexible-install.patch.patch
Patch3:     0004-meego-rpm-config-xzdebuginfo.patch.patch
Patch4:     0005-meego-rpm-config-0.18-wnopsabi.patch.patch
Patch5:     0006-meego-rpm-config-0.18-replace-mno-thumb-with-marm.pa.patch
Patch6:     0007-Rename-to-maui.patch

%description
MeeGo specific rpm configuration files.

%prep
%setup -q -n %{name}-%{version}
# 0001-meego-rpm-config-0.18-merchanges.patch.patch
%patch0 -p1
# 0002-meego-rpm-config-0.18-bashism.patch.patch
%patch1 -p1
# 0003-meego-rpm-config-0.18-flexible-install.patch.patch
%patch2 -p1
# 0004-meego-rpm-config-xzdebuginfo.patch.patch
%patch3 -p1
# 0005-meego-rpm-config-0.18-wnopsabi.patch.patch
%patch4 -p1
# 0006-meego-rpm-config-0.18-replace-mno-thumb-with-marm.pa.patch
%patch5 -p1
# 0007-Rename-to-maui.patch
%patch6 -p1

# >> setup
# << setup

%build
# >> build pre
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre

# >> install post
make DESTDIR=${RPM_BUILD_ROOT} install
# << install post

%files
%defattr(-,root,root,-)
# >> files
%{_prefix}/lib/rpm/maui
# << files
